language: python
services:
  - postgresql
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION='Django>=1.7,<1.8'
  - DJANGO_VERSION='Django>=1.8,<1.9'
  - DJANGO_VERSION='Django>=1.9,<1.10'
  - DJANGO_VERSION='Django>=1.10,<2.0'
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.7,<1.8'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.7,<1.8'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.9,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.10,<2.0'
    - python: "3.3"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO_VERSION='Django>=1.7,<1.8'
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install -q $DJANGO_VERSION
  - pip install -q django-model-utils flake8 psycopg2 six swapper tox tqdm
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database django_cities;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d django_cities
script:
  - flake8 --ignore=E501
  - PYTHONPATH=. python test_project/manage.py test test_app --noinput
